export default [
  {
    header: 'Components',
    items : [
      require('./demos/code.js').default,
      require('./demos/button.js').default,
      require('./demos/loading.js').default,
      require('./demos/loading-overlay.js').default,
      require('./demos/init-wrapper.js').default,
      require('./demos/image.js').default,
      require('./demos/upload-image.js').default,
      require('./demos/dropdown.js').default,
      require('./demos/progress-bar.js').default,
      require('./demos/dropzone.js').default,
      require('./demos/select-file.js').default,
      require('./demos/truncate-text.js').default,
      require('./demos/form.js').default,
      require('./demos/image-carousel.js').default,
      require('./demos/modal.js').default,
      require('./demos/hover-display.js').default,
      require('./demos/alert.js').default,
      require('./demos/app-shell.js').default,
      require('./demos/themed-form.js').default,
      require('./demos/table.js').default,
    ],
  },
  {
    header: 'Layout',
    items : [
      require('./demos/sidebar.js').default,
      require('./demos/left-middle-right.js').default,
      require('./demos/row.js').default,
    ],
  },
]
